@host = localhost:3000
@inDate = 2021-06-13
@outDate = 2021-06-15
@rooms = 1
@adults = 2
@destination = tulum

#min results : paris texas
#medium results: tulum
#max results: madrid

GET http://{{host}}/booking-com?inDate={{inDate}}&outDate={{outDate}}&rooms={{rooms}}&adults={{adults}}&destination={{destination}}
###

GET http://{{host}}/booking-com/clean-cache
###

GET https://scraper.travelnet.com.mx/booking-com?inDate={{inDate}}&outDate={{outDate}}&rooms={{rooms}}&adults={{adults}}&destination={{destination}}
###

GET https://scraper.travelnet.com.mx/booking-com/clean-cache
